What is Numpy?

 NumPy is the fundamental package for scientific computing in python Library that provides a multidimensional array object, various derived objects(Such as masked array and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier Transfor, basic linear algebra, basic statical operations, random simulation and much more.

At the core of the NumPy Package, is the ndarray object. this encapsulates n-dimensional arrays of homogeneous data types

Made in C and Run in Python

Numpy Array Vs Python Sequences

*   NumPy arrays have a fixed size at creation, unlike Python Lists(which can grow dynamically). Changing the size of an ndarray with create a new array and delete the output.
*   The elements in a  NumPy array are all required to be the same data Type, and thus will be the same size in memory 
*   NumPy arrays faciliates advanced mathematicals and other types of operations on large numbers of data. Typically, such operations are exected more  efficiently and with less code than is possible using Python's Built-in Sequence.

*   A growing plethors of scientific and mathematical Pythons- based Package are using NumPy  arrays; through these typically support Python sequence input, they convert such input to numPy arrays prior to processing, and they often output NumPy arrays.

Creating NumPy Array

In [1]:
import numpy as np

In [5]:
# vector
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [7]:
# 2D and 3D
b  = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3D or Tensor 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# dtype
f= np.array([1,2,3],dtype = float)
b= np.array([1,2,3],dtype = bool)
c = np.array([1,2,3],dtype=  complex)
print(f,b,c)

[1. 2. 3.] [ True  True  True] [1.+0.j 2.+0.j 3.+0.j]


In [13]:
#  np.arange  similiar to range in python
np.arange(2,5)

array([2, 3, 4])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# np.ones and np.zeros
# np.ones ---->  used to intialoze the arrays by 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# np.random ---> Generate a Number betweeen 0 and 1
np.random.random((3,4))

array([[0.49143423, 0.13022518, 0.80422356, 0.68739178],
       [0.30209973, 0.77902452, 0.13260505, 0.8957607 ],
       [0.1843029 , 0.00635584, 0.14277205, 0.39403431]])

In [25]:
# np.linspace--> it can generate a linear space point a in  a given range. 
np.linspace(-10,10,9)     
# used in graph in Machine Leaarning.

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [26]:
# np.identity     -----> Print the Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [2]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1,a2 ,a3)

[0 1 2 3 4 5 6 7 8 9] [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
#ndim(number of Dimension)
d1 = a1.ndim
d2 = a2.ndim
d3 =  a3.ndim
print(d1,d2,d3)

1 2 3


In [5]:
# shape (shape of array)
d1 = a1.shape
d2 = a2.shape
d3 =  a3.shape
print(d1,d2,d3)

(10,) (3, 4) (2, 2, 2)


In [6]:
a3.size

8

In [7]:
# Size ----> Number of Items
a3.itemsize

4

In [8]:
print(a1.dtype)
print(a2.dtype)

int32
float64


Changing DataTypes

In [10]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

Array Operations

In [14]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# Scalar OPerations
# Arithimetic
print(a1*2)
print(a2**2) 
print(a1+2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [21]:
#relational 
a2 ==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

Vector Operations---> because It's happen between 2 NumPy Arrays

In [22]:
#   Arithimetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [23]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

Array Function

In [2]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[82., 40.,  6.],
       [11., 64., 60.],
       [44., 39., 17.]])

In [28]:
#   max/min.sum/prod
np.min(a1)

2.0

In [34]:
# axis = 0 -----> 0-col and 1 ->  only for COLUMNS
np.max(a1,axis=0)

array([59., 91., 37.])

In [35]:
# For Rows axis=1
np.max(a1,axis=1)

array([91., 85., 42.])

In [29]:
np.max(a1)

91.0

In [30]:
np.sum(a1)

346.0

In [31]:
np.prod(a1)

468066198600.0

Mean/median/std/var

In [3]:
np.mean(a1,axis=1)

array([42.66666667, 45.        , 33.33333333])

In [5]:
np.median(a1,axis=1)

array([40., 60., 39.])

In [7]:
np.std(a1,axis=1)

array([31.08411527, 24.0970261 , 11.72840806])

In [9]:
np.var(a1,axis=1)

array([966.22222222, 580.66666667, 137.55555556])

In [10]:
#Trigometric Function
np.sin(a1)

array([[ 0.31322878,  0.74511316, -0.2794155 ],
       [-0.99999021,  0.92002604, -0.30481062],
       [ 0.01770193,  0.96379539, -0.96139749]])

Dot Product   ---> product between two matrices

In [14]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [15]:
#log 
np.log(a1)

array([[4.40671925, 3.68887945, 1.79175947],
       [2.39789527, 4.15888308, 4.09434456],
       [3.78418963, 3.66356165, 2.83321334]])

In [17]:
# Exponents
np.exp(a1)

array([[4.09399696e+35, 2.35385267e+17, 4.03428793e+02],
       [5.98741417e+04, 6.23514908e+27, 1.14200739e+26],
       [1.28516001e+19, 8.65934004e+16, 2.41549528e+07]])

In [27]:
#   round/floor/cell
# np.round(np.random.random((2,3))*100)
np.floor(np.random.random((3,4))*100)

array([[68., 45., 35., 73.],
       [54., 16., 11., 30.],
       [29., 71., 45., 71.]])

Indexing and Slicing

In [28]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1[-1]

9

In [31]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
# Indexing in 2D Arrays
a2[1,2]

6

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
#indexing in Tensor
a3[1,0,1]

5

In [39]:
a3[0,0,1]

1

In [40]:
a3[1,1,0]

6

Slicing ----> Removing the multiple element from at once time

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1[2:5]

array([2, 3, 4])

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2[0,:]

array([0, 1, 2, 3])

In [47]:
a2[:,2]        # 3 column

array([ 2,  6, 10])

In [48]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
# All Corner Elemnt of arrays
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [52]:
a2[::2,1::2]        

array([[ 1,  3],
       [ 9, 11]])

In [57]:
a2[1,0::3]

array([4, 7])

slicing in Tensor

In [59]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a3[0,1,:]

array([3, 4, 5])

In [65]:
a3[1,:,1]

array([10, 13, 16])

In [66]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [68]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [72]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [73]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [74]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [76]:
# nditer can print all number present in any dimension of array
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Transpose

In [78]:
np.transpose(a2)
# or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Ravel ----> ravel convert any dimensional array into 2D Arrays

In [83]:
a2.ravel()
a3.ravel()
# or
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking  ---> we can add two or more numpy array of stackoff. 

Shape must have to same

Two Way--->
1.  horizontally 
2.  Vertically 

In [86]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Horizontal

In [88]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

Vertical Stacking

In [90]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting of arrays

In [91]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

horizontal Split

In [92]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

Vertical Split

In [94]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]