What is Numpy?

 NumPy is the fundamental package for scientific computing in python Library that provides a multidimensional array object, various derived objects(Such as masked array and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier Transfor, basic linear algebra, basic statical operations, random simulation and much more.

At the core of the NumPy Package, is the ndarray object. this encapsulates n-dimensional arrays of homogeneous data types

Made in C and Run in Python

Numpy Array Vs Python Sequences

*   NumPy arrays have a fixed size at creation, unlike Python Lists(which can grow dynamically). Changing the size of an ndarray with create a new array and delete the output.
*   The elements in a  NumPy array are all required to be the same data Type, and thus will be the same size in memory 
*   NumPy arrays faciliates advanced mathematicals and other types of operations on large numbers of data. Typically, such operations are exected more  efficiently and with less code than is possible using Python's Built-in Sequence.

*   A growing plethors of scientific and mathematical Pythons- based Package are using NumPy  arrays; through these typically support Python sequence input, they convert such input to numPy arrays prior to processing, and they often output NumPy arrays.

Creating NumPy Array

In [1]:
import numpy as np

In [5]:
# vector
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [7]:
# 2D and 3D
b  = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3D or Tensor 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# dtype
f= np.array([1,2,3],dtype = float)
b= np.array([1,2,3],dtype = bool)
c = np.array([1,2,3],dtype=  complex)
print(f,b,c)

[1. 2. 3.] [ True  True  True] [1.+0.j 2.+0.j 3.+0.j]


In [13]:
#  np.arange  similiar to range in python
np.arange(2,5)

array([2, 3, 4])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# np.ones and np.zeros
# np.ones ---->  used to intialoze the arrays by 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# np.random ---> Generate a Number betweeen 0 and 1
np.random.random((3,4))

array([[0.49143423, 0.13022518, 0.80422356, 0.68739178],
       [0.30209973, 0.77902452, 0.13260505, 0.8957607 ],
       [0.1843029 , 0.00635584, 0.14277205, 0.39403431]])

In [25]:
# np.linspace--> it can generate a linear space point a in  a given range. 
np.linspace(-10,10,9)     
# used in graph in Machine Leaarning.

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [26]:
# np.identity     -----> Print the Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])