# Functions for Numpy

## np.sort
Return a sorted copy of an arrays.

In [1]:
# code
import numpy as np

In [2]:
a  = np.random.randint(1,100,15)
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[97,  4, 53, 55],
       [19, 85, 15, 12],
       [14, 14, 75,  5],
       [45, 26, 94, 55],
       [29, 59, 12, 66],
       [86, 61, 38, 97]])

In [4]:
np.sort(a)

array([17, 25, 25, 27, 28, 37, 40, 58, 60, 62, 63, 66, 71, 77, 82])

In [5]:
# axis = 1 --> coloum by sorting 
# axis = 0 ---> row by sorting
np.sort(b,axis=1)

array([[ 4, 53, 55, 97],
       [12, 15, 19, 85],
       [ 5, 14, 14, 75],
       [26, 45, 55, 94],
       [12, 29, 59, 66],
       [38, 61, 86, 97]])

##  np.append
The numpy.append() appends values along the mentioned axis at the end of the array.

https://numpy.org/doc/stable/reference/generated/numpy.append.html


In [6]:
# Code
np.append(a,200)

array([ 28,  60,  17,  25,  62,  77,  58,  25,  82,  71,  27,  37,  66,
        40,  63, 200])

In [7]:
# append in 2D Arrays.
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[97.        ,  4.        , 53.        , 55.        ,  0.56662683],
       [19.        , 85.        , 15.        , 12.        ,  0.5838081 ],
       [14.        , 14.        , 75.        ,  5.        ,  0.63807919],
       [45.        , 26.        , 94.        , 55.        ,  0.47240166],
       [29.        , 59.        , 12.        , 66.        ,  0.80151923],
       [86.        , 61.        , 38.        , 97.        ,  0.73161144]])

## np.concatenate
numpy.concatenate() function concatenates a sequence of arrays along an existing axis.
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

it also replace vetical Stacking and horizontal Stacking.


In [8]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis =0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## np.unique
with the help of np.unique() method, we can get the unoque values from an arrays given as parameter in np.unique() method
https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [10]:
e = np.array([1,2,1,3,4,2,4,3,5,6,6,7])

In [11]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

## np.expand_dims
with the help of Numpy.expand_dims() method, we get the expanded dimensions of an arrays
we can expand the 1D Array into 2D and many more.
https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [12]:
# code
print(a)
print(a.shape)

[28 60 17 25 62 77 58 25 82 71 27 37 66 40 63]
(15,)


In [13]:
np.expand_dims(a,axis =0).shape

(1, 15)

In [14]:
np.expand_dims(a,axis =1).shape

(15, 1)

## np.where
The Numpy.where() functions returns the indices of elements in an input arrays where the given condition is satisfied.
https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [15]:
f = np.random.randint(0,500,15,dtype= int)
f

array([194, 334, 181, 178,  21,  24,  99, 318,  83, 264, 359,  83, 497,
       488, 485])

In [16]:
np.where(f>150,0,a)

array([ 0,  0,  0,  0, 62, 77, 58,  0, 82,  0,  0, 37,  0,  0,  0])

In [17]:
# find the indices with the values greater than 50
np.where(f>50)

(array([ 0,  1,  2,  3,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int64),)

In [18]:
# replace all values >50 with 0
np.where(a>50,0,a)

array([28,  0, 17, 25,  0,  0,  0, 25,  0,  0, 27, 37,  0, 40,  0])

In [19]:
np.where(a%2==0,0,a)

array([ 0,  0, 17, 25,  0, 77,  0, 25,  0, 71, 27, 37,  0,  0, 63])

## np.argmax
The numpy.argmax() function return indices of the max element of the arrays in a particular axis
https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [21]:
np.argmax(a)

8

In [22]:
print(b)
np.argmax(b,axis =1)

[[97  4 53 55]
 [19 85 15 12]
 [14 14 75  5]
 [45 26 94 55]
 [29 59 12 66]
 [86 61 38 97]]


array([0, 1, 2, 2, 3, 3], dtype=int64)

In [23]:
np.argmin(a)

2

In [24]:
np.argmin(b,axis =0)

array([2, 0, 4, 2], dtype=int64)

## np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of arrays elements over a given axis.
https://numpy.org/doc/stable/reference/generated/numpy.expand.cumsum.html

In [25]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [26]:
np.cumsum(a)

array([ 28,  88, 105, 130, 192, 269, 327, 352, 434, 505, 532, 569, 635,
       675, 738])

In [27]:
b

array([[97,  4, 53, 55],
       [19, 85, 15, 12],
       [14, 14, 75,  5],
       [45, 26, 94, 55],
       [29, 59, 12, 66],
       [86, 61, 38, 97]])

In [28]:
np.cumsum(b,axis=0)

array([[ 97,   4,  53,  55],
       [116,  89,  68,  67],
       [130, 103, 143,  72],
       [175, 129, 237, 127],
       [204, 188, 249, 193],
       [290, 249, 287, 290]])

### np.cumprod

In [29]:
np.cumprod(a)

array([         28,        1680,       28560,      714000,    44268000,
        -886331296,   132392384,  -985157696,   821447552, -1806765952,
       -1538040448, -1072921728, -2093357312, -2129913856, -1040586752])

## np.percentile
numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.
https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [30]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [31]:
np.percentile(a,100)

82.0

In [32]:
np.percentile(a,50)

58.0

In [33]:
np.percentile(a,0)

17.0

## np.histogram
Numpy has a built-in numpy.histogram() function which represent the frequency of data distribution in the graphical form.
https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [34]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [35]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 4, 1, 1, 1, 4, 2, 1, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef
Return pearson product-moment correlation coefficients. 

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [36]:
salary = np.array([2000,3000,2500,4000,10000,7000])
experience = np.array([1,2,1.5,4,10,8])

np.corrcoef(salary,experience)

array([[1.        , 0.98799168],
       [0.98799168, 1.        ]])

## np.isin
with the help of numpy.isin() method, we can see that one arrays having values are checked in a different numpy array having different element with different size

Checking the multiple item at onces
https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [38]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [40]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False])

In [41]:
a[np.isin(a,items)]

array([60, 40])

## np.flip   ---> Mirror Image
The numpy.flip() function reverse the order of arrays elements along the specific axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [42]:
a

array([28, 60, 17, 25, 62, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

In [43]:
np.flip(a)

array([63, 40, 66, 37, 27, 71, 82, 25, 58, 77, 62, 25, 17, 60, 28])

In [44]:
b

array([[97,  4, 53, 55],
       [19, 85, 15, 12],
       [14, 14, 75,  5],
       [45, 26, 94, 55],
       [29, 59, 12, 66],
       [86, 61, 38, 97]])

In [46]:
np.flip(b,axis =0)

array([[86, 61, 38, 97],
       [29, 59, 12, 66],
       [45, 26, 94, 55],
       [14, 14, 75,  5],
       [19, 85, 15, 12],
       [97,  4, 53, 55]])

In [47]:
np.flip(b,axis = 1)

array([[55, 53,  4, 97],
       [12, 15, 85, 19],
       [ 5, 75, 14, 14],
       [55, 94, 26, 45],
       [66, 12, 59, 29],
       [97, 38, 61, 86]])

## np.put---> editing the array PERMANENT Change
The numpy.put() function replace specific elements of an arrays with given values of p_arrays. Array indexed works on flattened array. 
https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [55]:
a

array([110,  53,  17,  25,  62,  77,  58,  25,  82,  71,  27,  37,  66,
        40,  63])

In [54]:
#  first and 2 element
np.put(a,[0,1],[110,53])

## np.delete
The Numpy.delete() function returns a new arrays with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [56]:
a

array([110,  53,  17,  25,  62,  77,  58,  25,  82,  71,  27,  37,  66,
        40,  63])

In [59]:
np.delete(a,[0,4,2])

array([53, 25, 77, 58, 25, 82, 71, 27, 37, 66, 40, 63])

## Set Functions
*   np.union 1d
*   np.intersect 1d
*   np.setdiff 1d
*   np.setxor 1d
*   np.in 1d

In [62]:
# union
m =  np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.intersect1d(m,n)

array([3, 4, 5])

In [67]:
np.setdiff1d(m,n)

array([1, 2])

In [68]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [71]:
np.in1d(m,5)

array([False, False, False, False,  True])

In [73]:
m[np.in1d(m,5)]

array([5])

## np.clip
numpy.clip() function is used to clip (limit) the values in an array.                  
https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [74]:
a

array([110,  53,  17,  25,  62,  77,  58,  25,  82,  71,  27,  37,  66,
        40,  63])

In [76]:
np.clip(a,a_min = 25,a_max=75)

array([75, 53, 25, 25, 62, 75, 58, 25, 75, 71, 27, 37, 66, 40, 63])