**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [14]:
#Code here
a = np.array([0,0,0,0,1,0,0,0,0,0])
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [33]:
#Code here
a= int(input("Enter the Value of a: "))
b= int(input("Enter the value of b: "))

c = np.random.rand(a,b)
print(c)
print(type(c))

avg = np.mean(c)
print(f"Average of the array: {avg}")



[[0.74527389 0.13345518]
 [0.74968719 0.31031308]]
<class 'numpy.ndarray'>
Average of the array: 0.48468233462567145


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [34]:
#Code here
def create_2DArray(a,b):
    result_arr =  np.zeros((a,b),dtype=int)
    result_arr[0, :]=1       #Top Row
    result_arr[-1, :]=1      #Last Row
    result_arr[:,0] =1       #Left Column
    result_arr[:,-1] = 1     #Right Column

    return result_arr

a  =int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
create_2DArray(a,b)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [3]:
#Code here
a = np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [8]:
#Code here
# No we can't make the identity matrix of 3,4 using "np.identity(n)"
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [23]:
#Code here
my_matrix = np.arange(5).reshape((5,1)) + np.arange(5)
my_matrix1 = np.tile(np.arange(5),(5,1))
print("Matrix of 5x5 by adding the row by ONE")
print(my_matrix)
print("Matix of 5x5 by ranging row from 0 to 4:")
print(my_matrix1)

Matrix of 5x5 by adding the row by ONE
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
Matix of 5x5 by ranging row from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [27]:
np.random.randint(1,100,size=(10,2))

array([[64, 60],
       [21, 33],
       [76, 58],
       [22, 89],
       [49, 91],
       [59, 42],
       [92, 60],
       [80, 15],
       [62, 62],
       [47, 62]])

In [26]:
#code here
np.random.seed(42)
random_coordinate = np.random.randint(1,100,size = (10,2))
point = np.array([2,3])
distances = np.sqrt(np.sum((random_coordinate-point)**2,axis=1)).astype(int)
print(distances)

[102  70  61 116 102  88  19  51  90  36]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
#Code here
shape = (6,7,8)
index_100th_element = np.unravel_index(99,shape)
print(index_100th_element)

(1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [42]:
#Code here
original_array = np.array([1,2,3,4,-8,-10])
reversed_array = original_array.astype(float)[::-1]
reversed_array

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [55]:
#Code here
a = np.array([1,2,4,5,10])
element_count  = np.count_nonzero(a)
print("element count: ",element_count)

element count:  5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [20]:
#Code here
def softmax(x):
    if len(x.shape)!=1:
        raise ValueError("Input must be a 1D Numpy array")
    
    exp_x = np.exp(x - np.max(x))
    softmax_value= exp_x /np.sum(exp_x)

    return softmax_value

input_array = np.array([33.5,23.5,12.7,76.6])
result = softmax(input_array)
print(result)

[1.91384971e-19 8.68886423e-24 1.77248515e-28 1.00000000e+00]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [25]:
#Code here
def stack_array(*arrays):
    # check if all input are numpy arrays
    if any(not isinstance(arr,np.ndarray) for arr in arrays):
        raise ValueError("All input must be NumPy Arrays.")

    result = np.vstack(arrays)

    return result

arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(10,30).reshape(4,5)

result = stack_array(arr1,arr2)
print(result)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [33]:
#Code here
import time
def date_array(start_date_str,end_date_str):
    if not(isinstance(start_date_str,str) and isinstance(end_date_str,str)):
        raise ValueError("Both input must be String")
    
    start_date = np.datetime64(start_date_str)
    end_date = np.datetime64(end_date_str)

    date_range = np.arange(start_date,end_date + np.timedelta64(1,'D'),dtype = 'datetime64[D]')
    return date_range

start_date_str = '2022-01-01'
end_date_str = '2022-01-10'
result_date = date_array(start_date_str,end_date_str)

print(result_date)

['2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04' '2022-01-05'
 '2022-01-06' '2022-01-07' '2022-01-08' '2022-01-09' '2022-01-10']


###`Q-14:` Subtract the mean of each row from a matrix.

In [39]:
#code here
def substract_row_mean(matrix):
    if not isinstance(matrix, np.ndarray):
        raise ValueError("Input must be a numpy array")
    
    row_mean= np.mean(matrix,axis =1,keepdims=True)
    result_matrix = matrix - row_mean

    return result_matrix

input_matrix = np.arange(30,42).reshape(3,4)
result = substract_row_mean(input_matrix)
print(result)

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [41]:
#Code here
def swap_col(matrix):
    if not isinstance(matrix,np.ndarray):
        raise ValueError("Input Must be a NumPy Arrays.")
    
    # check if the array must contain more than 1 column.
    if matrix.shape[1]<2:
        raise ValueError("Input Matrix must be a more than two column")
    
    matrix[:,[0,1]]=matrix[:, [ 1,0]]
    return matrix

array  = np.arange(12).reshape(3,4)
print(array)
result = swap_col(array)
print(f"Resultant matrix is {result}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Resultant matrix is [[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [58]:
#Code here
a  = np.arange(10)
a[a%2 !=0] =-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [70]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [42]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[4219, 6639, 6868, 2087, 2273],
       [2417, 6656,  234, 3272, 8975],
       [5488, 9577, 5403, 6324, 8754],
       [4547, 5080, 5123, 5131, 8723],
       [6245, 7838,  679, 2436, 5360],
       [9154, 9810, 1848, 8196, 8451],
       [8847, 7109, 7011, 3960, 6477],
       [9825, 5898,  597, 1223, 2699]])

In [50]:
#Code here
alternate_col = arr1[:,::2]
print("Every alternate column of the array")
print(alternate_col,"\n\n")

Normalized_array  = (arr1-arr1.min(axis=0))/(arr1.max(axis=0)-arr1.min(axis =0))
print("NOrmalization of given Array\n")
print(Normalized_array)

Every alternate column of the array
[[4219 6868 2273]
 [2417  234 8975]
 [5488 5403 8754]
 [4547 5123 8723]
 [6245  679 5360]
 [9154 1848 8451]
 [8847 7011 6477]
 [9825  597 2699]] 


NOrmalization of given Array

[[0.24325054 0.32959831 0.97889922 0.1239065  0.        ]
 [0.         0.33319239 0.         0.2938477  1.        ]
 [0.41455184 0.95073996 0.76272687 0.73153592 0.96702477]
 [0.287527   0.         0.72141065 0.56044744 0.96239928]
 [0.51673866 0.58308668 0.06566327 0.17395669 0.46060877]
 [0.90942225 1.         0.23815848 1.         0.92181438]
 [0.86798056 0.42896406 1.         0.39251398 0.62727544]
 [1.         0.17293869 0.05356352 0.         0.06356312]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [4]:
#Code here
def nthMax(arr,n):
    if n>len(arr):
        raise IndexError("nth is out of Limit")
    arr.sort()
    return arr[-n]

a  = np.array([1,23,12,90,34,23,100])
nthMax(a,3)

34

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [18]:
#code here
a = np.array([1,2,3])
l = len(a)
r1 = np.repeat(a,l)
r2 = np.tile(a,l)
# np.hstack is using only in LIST
np.hstack([r1,r2])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])